---
- hosts: tomcat
  vars:
    tomcat_dir: /usr/share/tomcat9
  tasks:
    - name: Устанавливаем JDK
      apt:
        pkg: default-jdk
        state: present
        update_cache: true
      notify:
        - install jdk

    - name: создаем группу tomcat
      group:
        name: tomcat
      notify:
        - Создаем группу tomcat

    - name: пользователь tomcat
      user:
        name: tomcat
        group: tomcat
        createhome: false
      notify:
        - Создаем пользователя tomcat

    - name: "папка для томката {{ tomcat_dir }}"
      file:
        path: "{{ tomcat_dir }}"
        state: directory
        mode: 0755
      notify:
        - Создаем папку

    - name: качаем и распаковываем
      unarchive:
        src: https://apache-mirror.rbc.ru/pub/apache/tomcat/tomcat-9/v9.0.38/bin/apache-tomcat-9.0.38.tar.gz
        dest: "{{ tomcat_dir }}"
        remote_src: true
        extra_opts: [--strip-components=1]
      notify:
        - Распаковываем Томкат

    - name: Права
      file:
        path: "{{ tomcat_dir }}"
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: true
        state: directory
      notify:
        - Назначаем права

    - name: Стартуем томкат
      command: "{{ tomcat_dir }}/bin/startup.sh"
      notify:
        - Собираем проект


- hosts: maven
  tasks:
    - name: Устанавливаем Maven
      apt:
        pkg: maven
        state: installed
        update_cache: true
      notify:
        - Устанавливаем maven

    - name: Клонируем проект
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp
      notify:
        - Клонируем проект

    - name: Собираем проект
      command: mvn package -f /tmp/boxfuse-sample-java-war-hello/pom.xml
      notify:
        - Собираем проект

    - name: Перетаскиваем проект на прод
      synchronize:
        src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0/*
        dest: /usr/local/tomcat/webapps/ROOT
        mode: pull
      delegate_to: tomcat
