---

# сборка
- hosts: maven
  vars:
    proj_dir: /tmp/boxfuse-sample-java-war-hello

  tasks:
    - name: Устанавливаем Python
      apt:
        pkg: python
        state: present
        update_cache: true

    - name: Устанавливаем Maven
      apt:
        pkg: maven
        state: present
        update_cache: true

    - name: Подчищаем /tmp
      file:
        path: "{{ proj_dir }}"
        state: absent

    - name: Клонируем проект
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: "{{ proj_dir }}"

    - name: Собираем проект
      command: "mvn package -f {{ proj_dir }}/pom.xml"

    - name: Упаковываем
      command: "tar -czf /tmp/hello.tar.gz {{ proj_dir }}/target/hello-1.0"
      warn: false

    - name: Утягиваем проект
      copy:
        src: "/tmp/hello.tar.gz"
        dest: "/tmp"
        remote_src: true


# prod
- hosts: tomcat
  vars:
    tomcat_dir: /usr/share/tomcat9
    www_root: /usr/local/tomcat/webapps/ROOT

  tasks:
    - name: Устанавливаем JDK
      apt:
        pkg: default-jdk
        state: present
        update_cache: true

    - name: создаем группу tomcat
      group:
        name: tomcat

    - name: пользователь tomcat
      user:
        name: tomcat
        group: tomcat
        createhome: false

    - name: "папка для томката {{ tomcat_dir }}"
      file:
        path: "{{ tomcat_dir }}"
        state: directory
        mode: 0755

    - name: качаем и распаковываем
      unarchive:
        src: https://apache-mirror.rbc.ru/pub/apache/tomcat/tomcat-9/v9.0.38/bin/apache-tomcat-9.0.38.tar.gz
        dest: "{{ tomcat_dir }}"
        remote_src: true
        extra_opts: [--strip-components=1]

    - name: назначаем томкат на 80 порт
      lineinfile:
        path: "{{ tomcat_dir }}/conf/server.xml"
        regexp: 'port=\"8080\"'
        line: 'port=\"80\"'

    - name: Права
      file:
        path: "{{ tomcat_dir }}"
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: true
        state: directory

    - name: Подчищаем корневую директорию томката
      command: "rm -rf {{ www_root }}/*"
      warn: false

    - name: разворачиваем в корень
      unarchive:
        src: /tmp/hello.tar.gz
        dest: "{{ www_root }}"

    - name: Стартуем томкат
      command: "{{ tomcat_dir }}/bin/startup.sh"
