---

# сборка
- hosts: maven
  vars:
    proj_dir: /tmp/boxfuse-sample-java-war-hello

  tasks:
    - name: Устанавливаем Python
      apt:
        pkg: python
        state: present
        update_cache: true

    - name: Устанавливаем Maven
      apt:
        pkg: maven
        state: present
        update_cache: true

    - name: Подчищаем /tmp
      file:
        path: "{{ proj_dir }}"
        state: absent

    - name: Клонируем проект
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: "{{ proj_dir }}"

    - name: Собираем проект
      command: "mvn package -f {{ proj_dir }}/pom.xml"

    - name: Упаковываем
      command: 
        cmd: "tar -czf /tmp/hello.tar.gz {{ proj_dir }}/target/hello-1.0"
        warn: false

    - name: Утягиваем проект
      fetch:
        src: "/tmp/hello.tar.gz"
        dest: "/tmp/"
        flat: true        

# prod
- hosts: tomcat
  vars:
    tomcat_dir: /usr/share/tomcat9
    www_root: "/usr/share/tomcat9-root/default-root"

  tasks:
    - name: Ставим Tomcat 9
      become: yes
      apt: 
        pkg: {{ item }} 
        state: latest 
        update_cache: yes 
        cache_valid_time: 3600
      with_items:
        - tomcat9

    - name: Подчищаем корневую директорию томката
      command: 
        cmd: "rm -rf {{ www_root }}/*"
        warn: false

    - name: разворачиваем в корень
      unarchive:
        src: /tmp/hello.tar.gz
        dest: "{{ www_root }}/"

    - name: Стартуем томкат
      shell: "{{ tomcat_dir }}/bin/startup.sh"
