---
- hosts: tomcat
  vars:
    tomcat_dir: /usr/share/tomcat9
  tasks:
    - name: Устанавливаем JDK
      apt:
        pkg: default-jdk
        state: present
        update_cache: true

    - name: создаем группу tomcat
      group:
        name: tomcat

    - name: пользователь tomcat
      user:
        name: tomcat
        group: tomcat
        createhome: false

    - name: "папка для томката {{ tomcat_dir }}"
      file:
        path: "{{ tomcat_dir }}"
        state: directory
        mode: 0755

    - name: качаем и распаковываем
      unarchive:
        src: https://apache-mirror.rbc.ru/pub/apache/tomcat/tomcat-9/v9.0.38/bin/apache-tomcat-9.0.38.tar.gz
        dest: "{{ tomcat_dir }}"
        remote_src: true
        extra_opts: [--strip-components=1]

    - name: Права
      file:
        path: "{{ tomcat_dir }}"
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: true
        state: directory

    - name: Стартуем томкат
      command: "{{ tomcat_dir }}/bin/startup.sh"


- hosts: maven
    vars:
      proj_dir: /tmp/boxfuse-sample-java-war-hello
  tasks:
    - name: Устанавливаем Maven
      apt:
        pkg: maven
        state: installed
        update_cache: true

    - name: Подчищаем /tmp
      file:
        path: "{{ proj_dir }}"
        state: absent

    - name: Клонируем проект
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: "{{ proj_dir }}"

    - name: Собираем проект
      command: "mvn package -f {{ proj_dir }}/pom.xml"

    - name: Перетаскиваем проект на прод
      synchronize:
        src: "{{ proj_dir }}/target/hello-1.0/*"
        dest: /usr/local/tomcat/webapps/ROOT
        mode: pull
      delegate_to: tomcat
